import 'package:flutter/material.dart';
import 'package:pos_desktop/core/utils/toast_helper.dart'; // ✅ correct file
import 'package:pos_desktop/core/utils/validators.dart';
import 'package:pos_desktop/domain/entities/owner_entity.dart';
import 'package:pos_desktop/domain/usecases/add_owner_usecase.dart';
import 'package:pos_desktop/domain/repositories/owner_repository.dart';

class OwnerSignupController {
  final AddOwnerUseCase _addOwnerUseCase;

  OwnerSignupController(OwnerRepository repository)
    : _addOwnerUseCase = AddOwnerUseCase(repository);

  // --- Text controllers ---
  final shopName = TextEditingController();
  final ownerName = TextEditingController();
  final email = TextEditingController();
  final password = TextEditingController();
  final confirmPassword = TextEditingController();
  final contact = TextEditingController();

  final formKey = GlobalKey<FormState>();
  bool isLoading = false;

  // --- Validation methods ---
  String? validateShopName(String? v) =>
      Validators.notEmpty(v, fieldName: 'Shop Name');
  String? validateOwnerName(String? v) =>
      Validators.notEmpty(v, fieldName: 'Owner Name');

  String? validateEmail(String? v) {
    final err = Validators.notEmpty(v, fieldName: 'Email');
    if (err != null) return err;
    final regex = RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$');
    if (!regex.hasMatch(v!)) return 'Enter a valid email address';
    return null;
  }

  String? validatePassword(String? v) {
    final err = Validators.notEmpty(v, fieldName: 'Password');
    if (err != null) return err;
    if (v!.length < 6) return 'Password must be at least 6 characters';
    return null;
  }

  String? validateConfirmPassword(String? v) {
    final err = Validators.notEmpty(v, fieldName: 'Confirm Password');
    if (err != null) return err;
    if (v != password.text) return 'Passwords do not match';
    return null;
  }

  String? validateContact(String? v) {
    if (v == null || v.isEmpty) return 'Contact number is required';
    final regex = RegExp(r'^[0-9+\-\s()]{10,}$');
    if (!regex.hasMatch(v)) return 'Enter a valid contact number';
    return null;
  }

  // ==========================================================
  // 🟢 SIGNUP LOGIC (new clean flow)
  // ==========================================================
  Future<int?> signup(BuildContext context) async {
    if (!formKey.currentState!.validate()) return null;

    try {
      isLoading = true;

      final ownerEntity = OwnerEntity(
        id: '', // will be generated by DB
        name: ownerName.text.trim(),
        email: email.text.trim(),
        storeName: shopName.text.trim(),
        password: password.text.trim(),
        contact: contact.text.trim(),
        superAdminId: null,
        status: OwnerStatus.pending,
        createdAt: DateTime.now(),
      );

      // ✅ Get the ownerId returned from the use case
      final ownerId = await _addOwnerUseCase.call(ownerEntity);

      if (context.mounted) {
        AppToast.show(
          context,
          message: 'Owner registered successfully! Proceed to select plan.',
          type: ToastType.success,
        );
      }
    } catch (e) {
      if (context.mounted) {
        AppToast.show(
          context,
          message: 'Failed to register owner: $e',
          type: ToastType.error,
        );
      }
      return null;
    } finally {
      isLoading = false;
    }
  }

  void clearForm() {
    shopName.clear();
    ownerName.clear();
    email.clear();
    password.clear();
    confirmPassword.clear();
    contact.clear();
  }

  Map<String, String> getFormData() => {
    'shopName': shopName.text.trim(),
    'ownerName': ownerName.text.trim(),
    'email': email.text.trim(),
    'password': password.text.trim(),
    'contact': contact.text.trim(),
  };

  void dispose() {
    shopName.dispose();
    ownerName.dispose();
    email.dispose();
    password.dispose();
    confirmPassword.dispose();
    contact.dispose();
  }
}
